/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'ankale' at '9/21/16 2:55 PM' with Gradle 2.14
 *
 * @author ankale, @date 9/21/16 2:55 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
